### PR TITLE
Fix Heroku button and README.

### PR DESCRIPTION
**Pull request by EtherTyper**
In my [deployed test](https://ftc-root.herokuapp.com), I'm only getting 500 errors on the main page, probably because the team location data was removed. However, on pages that don't use this data, like [the About page](https://ftc-root.herokuapp.com/pages/about), it works just fine.

I'll try to have `app.json` download the data upon deployment in a later pull request.

Thanks,
@EtherTyper

P.S. Are you guys thinking of giving the project an open source license?

### CODE REVIEW

**Comment by TheReddKing** [comment]
The main page uses Google Maps API. The key I use is under a whitelisted domain setting. I think that is the main problem. Not sure though

**Comment by EtherTyper** [comment]
@TheReddKing Interesting. Should I make [this line](https://github.com/TheReddKing/FTCRoot/blob/365e2a966070e4ee8ebcdcccbf5ded09907585ae/app/views/layouts/application.html.erb#L13) use an environment variable instead?

**Comment by EtherTyper** [comment]
@TheReddKing Wait&mdash;that reference to Google Maps API is client-side, meaning it wouldn't have caused a 500 error, unless if you have some kind of server-side external resource scanner.

Is that the case?

**Comment by TheReddKing** [comment]
Can you post the production logs on heroku?
It's under "more" in the top right corner when you click on the app

**Comment by EtherTyper** [comment]
@TheReddKing Sure thing! I didn't know you could do that, just one second...

**Comment by EtherTyper** [comment]
Yep, definitely looks like a problem with setup of the Google Maps gem:

```
2017-01-02T21:11:05.339886+00:00 app[web.1]: I, [2017-01-02T21:11:05.339829 #4]  INFO -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4] Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.0ms)
2017-01-02T21:11:05.341619+00:00 app[web.1]: F, [2017-01-02T21:11:05.341566 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     78:       var mak;
2017-01-02T21:11:05.341211+00:00 app[web.1]:                               ^
2017-01-02T21:11:05.341544+00:00 app[web.1]: F, [2017-01-02T21:11:05.341490 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     77:       var infowindow = new google.maps.InfoWindow();
2017-01-02T21:11:05.341920+00:00 app[web.1]: F, [2017-01-02T21:11:05.341865 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     82:         markers.push(mak);
2017-01-02T21:11:05.341705+00:00 app[web.1]: F, [2017-01-02T21:11:05.341638 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     79:       var e;
2017-01-02T21:11:05.341778+00:00 app[web.1]: F, [2017-01-02T21:11:05.341707 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     80:       <% @hello.each do |team| %>
2017-01-02T21:11:05.341859+00:00 app[web.1]: F, [2017-01-02T21:11:05.341798 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     81:         mak = new google.maps.Marker({map: map,position: new google.maps.LatLng(<%= team.location_lat %>, <%= team.location_long %>),title: "<%= team.name %>",address: "<%= team.location %>",id: "<%= team.id %>"});
2017-01-02T21:11:05.341986+00:00 app[web.1]: F, [2017-01-02T21:11:05.341927 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]     83:        <% end %>
2017-01-02T21:11:05.342043+00:00 app[web.1]: F, [2017-01-02T21:11:05.341994 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4]   
2017-01-02T21:11:05.342113+00:00 app[web.1]: F, [2017-01-02T21:11:05.342063 #4] FATAL -- : [e59adea8-6c38-46e3-a1b4-2789c1e940d4] app/views/tools/map.html.erb:80:in `_app_views_tools_map_html_erb___1795954318917285406_70355362950480'
```

**Comment by TheReddKing** [comment]
Did you migrate the database?

**Comment by EtherTyper** [comment]
@TheReddKing No, how are you supposed to?

**Pull request merged**
